# config.yaml
using_real_robot: false
robot_ip: "192.168.123.161"
# robot_pose_topic: "/unitree_go1/pose"
robot_pose_y_up_topic: "/mocap_pose_topic/go1_2_pose"
robot_pose_z_up_topic: "/unitree_go1/pose"    # /unitree_go1/pose
# object_pose_topic: "/mocap_sim/ball"
object_pose_y_up_topic: "/flying_object/pose_y_up"
object_pose_z_up_topic: "/flying_object/pose_z_up"

trigger_dummy_run_topic: "/mocap_pose_topic/chip_star_pose"
predicted_impact_point_z_up_topic: "/move_base_simple/goal"           # "/NAE/impact_point"   "/move_base_simple/goal"
predicted_traj_z_up_topic: "NAE/predicted_traj"

real_trajectory_viz_topic: "/rviz_flying_object_trajectory"
object_pose_z_up_viz_topic: "/rviz_flying_object"
realtime_basket_pose_viz_topic: "/rviz_basket_pose"


trajectory_predictor:
  predict_schedule_step: 2
  ignore_first_predictions: 0
  rate: 20
  pub_impact_point_with_z_up: true

rocat_sim_manager:
  trigger_n_thow_time_gap_sim: 0.3
  catching_distance: 0.6
  catching_orientation_dev_deg_thres: 20
  
impact_checker:
  control_tolerance_xy:
    - 0.125
    - 0.1
    - 0.07
    - 0.05
    - 0.025

high_level_controller:
  gait_type: 2
  rate: 50
  control_tolerance_xy: 0.05
  modify_z_up_goal: false
  modify_z_up_robot_pose: false
  dummy_run_time: 1.0
  dummy_run_vel: 0.3
  max_control_time: 10.0
  active_zone_x: [-1000, 1000]
  active_zone_y: [-1000, 1000]
  dummy_zone_x: [-1000, 1000]
  dummy_zone_y: [-1000, 1000]

  pid_x: [2.5, 0.0, 0.0]
  pid_y: [2.0, 0.0, 0.0]
  pid_theta: [0.5, 0.0, 0.0]
  deadband_xytheta: [0.0, 0.0, 3.0]

  vx_range: [-1.0, 2.0]
  vy_range: [-1.0, 1.0]
  wz_range: [-1.0, 1.0]



# catching_height: null

# ## NAE
# model_dir: '/home/huynn/huynn_ws/trajectory_prediction/nae_static/training_scripts/V-general-except-U-N-J-Q-O/models/V-3-1-PC3-general-except-U-N-J-Q-O-in30-out10_model'
# model_epoch_idx: 30000 
# model_name: 'NAE'

# ## NAE-ID
# model_dir : '/home/huynn/huynn_ws/trajectory_prediction/nae_static/training_scripts/V-general-except-U-N-J-Q-O/models/V-4-1-PC1-general-ONE-HOT-except-U-N-J-Q-O-in30-out10_model'
# model_epoch_idx : 29999
# model_name : 'NAE-ID'

# ## LSTMencoder
# model_dir: '/home/huynn/huynn_ws/trajectory_prediction/nae_static/training_scripts/0-Phase-2/LSTMencoder/Vph2-v0-1-PCNAIST-server-GEN-EXCEPT-U-N-J-Q-O-lstmENCODER-in30-out10_model'
# model_epoch_idx: best_model_ade 
# model_name: 'LSTMencoder'

## LSTMencoder-CLF
model_dir: '/home/huynn/huynn_ws/trajectory_prediction/nae_static/training_scripts/0-phase-4/models-phase-4-week-2-cont-train/Vph4-v1-1-w1-PCNAIST-server-GEN-EXCEPT-U-N-J-Q-O-lstmENCODER-in30-out10_model'
model_epoch_idx: best_model_ade 
model_name: 'LSTMencoder-CLF-w1-1CLFlayer'

object_name: ball     
# UNSEEN: cookie_box water_bottle paper_cup noodle_cup cap
                              # ball              
                              # big_sized_plane   
                              # boomerang         
                              # cardboard         
                              # ring_frisbee
                          
