# config.yaml
using_real_robot: false
robot_ip: "192.168.123.161"
# robot_pose_topic: "/unitree_go1/pose"
robot_pose_y_up_topic: "/mocap_pose_topic/go1_2_pose"
robot_pose_z_up_topic: "/unitree_go1/pose"    # /unitree_go1/pose
# object_pose_topic: "/mocap_sim/ball"
object_pose_y_up_topic: "/flying_object/pose_y_up"
object_pose_z_up_topic: "/flying_object/pose_z_up"

trigger_dummy_run_topic: "/mocap_pose_topic/chip_star_pose"
predicted_impact_point_z_up_topic: "/move_base_simple/goal"           # "/NAE/impact_point"   "/move_base_simple/goal"
predicted_traj_z_up_topic: "NAE/predicted_traj"

real_trajectory_viz_topic: "/rviz_flying_object_trajectory"
object_pose_z_up_viz_topic: "/rviz_flying_object"
realtime_basket_pose_viz_topic: "/rviz_basket_pose"

point_mass_sim:
  max_vel_x: 2.5
  max_vel_y: 1.0
  max_vel_theta: 1.0

  max_acc_x: 1.5
  max_acc_y: 1.0
  max_acc_theta: 1.0
  
  friction: 0.0

trajectory_predictor:
  predict_schedule_step: 2
  ignore_first_predictions: 0
  rate: 10
  pub_impact_point_with_z_up: true
  interpolate_raw_pos_data: false

rocat_sim_manager:
  trigger_ctrl:
    enable: false
    trigger_n_thow_time_gap_sim: 0.15 # no meaning
  init_dist_by_flight_time:
    enable: false
    init_dist_min_thres: 0.2
    init_dist_safety_factor: 0.7
  # if init_dist_by_flight_time.enable is false
  init_catching_distance_hardcoded: 0.3 # Null
  sample_within_circle: true

  min_trajectory_len_thres: 100           # skip if trajectory length is less than this value
  # catching_distance: 0.4
  # catching_orientation_dev_deg_thre_ranges: [[-15, 15], [170, 190]]
  catching_orientation_dev_deg_thre_ranges: [[-180, 180]]       #[[-10, 10]]
  wait_time_b4_trigger_ctrl: 0.5    # no meaning
  wait_time_after_robot_reset: 0.5  # no meaning
  init_dist_min_thres: 0.2
  
impact_checker:
  control_tolerance_xy:
    - 0.2
    - 0.17
    - 0.15
    - 0.125
    - 0.1
    - 0.07
    - 0.05
    - 0.025

high_level_controller:
  gait_type: 2
  rate: 50
  control_tolerance_xy: 0.025
  modify_z_up_goal: false
  modify_z_up_robot_pose: false
  dummy_run_time: 1.0
  dummy_run_vel: 0.3
  max_control_time: 10.0
  active_zone_x: [-1000, 1000]
  active_zone_y: [-1000, 1000]
  dummy_zone_x: [-1000, 1000]
  dummy_zone_y: [-1000, 1000]

  pid_x: [2.5, 0.0, 0.0]
  pid_y: [2.0, 0.0, 0.0]
  pid_theta: [0.5, 0.0, 0.0]
  deadband_xytheta: [0.0, 0.0, 3.0]

  vx_range: [-1.0, 2.5]
  vy_range: [-1.0, 1.0]
  wz_range: [-1.0, 1.0]



# ====================  Newton  ====================
# ## Newton
# model_dir: '$(env NAE_DIR)/training_scripts/0-Phase-4/models/1LSTMEncoder/Vph4-v1-1-w1-PCNAIST-server-GEN-EXCEPT-U-N-J-Q-O-lstmENCODER-in30-out10_model'
# model_epoch_idx: best_model_ade 
# model_name: 'Newton'

# ====================  Sliding Window Models  ====================
# ## NAE
# model_dir: $(env NAE_DIR)/training_scripts/V-general-except-U-N-J-Q-O/models/V-3-1-PC3-general-except-U-N-J-Q-O-in30-out10_model
# model_epoch_idx: 30000 
# model_name: 'NAE'
# model_training_type: 'sliding_window' # 'free_running' or 'sliding_window'

# ## NAE-ID
# model_dir : $(env NAE_DIR)/training_scripts/V-general-except-U-N-J-Q-O/models/V-4-1-PC1-general-ONE-HOT-except-U-N-J-Q-O-in30-out10_model
# model_epoch_idx : 29999
# model_name : 'NAE-ID'
# model_training_type: 'sliding_window' # 'free_running' or 'sliding_window'

# ## LSTMencoder
# model_dir: '$(env NAE_DIR)/training_scripts/0-Phase-4/models/1LSTMEncoder/Vph2-v0-1-PCNAIST-server-GEN-EXCEPT-U-N-J-Q-O-lstmENCODER-in30-out10_model'
# model_epoch_idx: best_model_ade 
# model_name: 'DFEwoLD'
# model_training_type: 'sliding_window' # 'free_running' or 'sliding_window'

# ## LSTMencoder-CLF
# model_dir: '$(env NAE_DIR)/training_scripts/0-Phase-4/models/1LSTMEncoder/Vph4-v1-1-w1-PCNAIST-server-GEN-EXCEPT-U-N-J-Q-O-lstmENCODER-in30-out10_model'
# model_epoch_idx: best_model_ade 
# model_name: 'DFE'
# model_training_type: 'sliding_window' # 'free_running' or 'sliding_window'

# ====================  Free Running Models  ====================
## DFE-W1 free running
model_dir: '$(env NAE_DIR)/training_scripts/0-phase-7/1-GEN/generalized_W7_fine_tune/models/V-ph7-1-DFEIEloss-v1-1-NAISTSER-GEN-LR_3e-05-W7_1_0-Pr2Imp-True-NByS-False-in30-outNone_model/model_17-07-2025_20-00-56_hiddensize128_inseq30_outpredNone'
model_epoch_idx: best_model_fe 
model_name: 'DFEIEW1'
model_training_type: 'free_running' # 'free_running' or 'sliding_window'

# object_name: cap     
# UNSEEN: 
      # cookie_box        -> 
      # water_bottle      -> 
      # paper_cup         -> 
      # noodle_cup        -> 
      # cap               -> 
# SEEN:
      # ball              -> 
      # big_sized_plane   -> 
      # boomerang         ->   
      # cardboard         -> 
      # ring_frisbee      -> 
                          
